### ISSUE TITLE
Analysis Subtype Consistency

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/nuclearnetwork_wp#125]
# Part 1
The `nuclearnetwork_display_subtypes()` pulls from the incorrect taxonomy for Posts. It currently pulls from the "Analysis Subtype" taxonomy, but it should pull from the "Content Types" taxonomy.

<img width="165" alt="Screen Shot 2021-09-09 at 10 16 33 AM" src="https://user-images.githubusercontent.com/1896496/132702767-7bb1ed31-0892-45d7-b1f1-1929bcef3177.png">

Within the Content Types, the subtype are the children of the main content type. See examples in the screen shot below.

<img width="736" alt="Screen Shot 2021-09-09 at 10 17 49 AM" src="https://user-images.githubusercontent.com/1896496/132703197-6da0867c-f150-49dc-9e2b-c4ad12726b23.png">

- [ ] Update function to pull from Content Types taxonomy
- [ ] Delete Analysis Subtypes taxonomy

## Part 2
For even better consistency, the "Events Type" taxonomy should also be removed and replaced with the "Content Types" taxonomy information. This is less urgent than fixing the analysis posts, though.

- [ ] Update function to pull from Content Types taxonomy
  - [ ] There might be other places where this taxonomy is used. You should check with @urchykli to be sure/dig around in the theme. 
- [ ] Update Events posts to be properly categorized under the Content Types taxonomy. This can be done using the Bulk Edit feature and should be done **before** deleting the Events Types taxonomy. Under Events --> Event Types, you can click on a number next to a taxonomy term and it will take a you to a list of posts tagged with that term. You can then use the bulk edit function to update those posts accordingly. See screenshots below.
- [ ] Delete Events Types taxonomy

<img width="550" alt="Screen Shot 2021-09-09 at 10 23 19 AM" src="https://user-images.githubusercontent.com/1896496/132704108-37632111-e923-4228-a4d8-d6e732b768f6.png">

Clicking on the "41" next to Conference will take you to [this list](https://csisngnndev.wpengine.com/wp-admin/edit.php?event_types=conference&post_type=events).
